Hydro-PED: flac.f90 File Reference
flac.f90 File Reference
Functions/Subroutines
subroutine efdlm (dt, event)
Calculates node velocity.
subroutine force_balance (n)
subroutine n_force_balance (dt)
subroutine boff_calc (dt, vvv)
Function Documentation
subroutine boff_calc (real(kind=8) dt, real(kind=8) vvv)
Definition at line 249 of file flac.f90.
References node_data::balance, sizes::boff, node_data::force, sizes::noff, sizes::np, and node_data::vel.
Referenced by drop(), and efdlm().
subroutine efdlm (real(kind=8) dt, logical event)
Calculates node velocity.
Uses Lagrangian method for force balance calculations.
Parameters:
[in] time step
[out] event
Definition at line 36 of file flac.f90.
References element_data::al_biot, element_data::alpha, node_data::balance, boff_calc(), elastic(), element_data::flag, node_data::force, force_balance(), n_force_balance(), sizes::ne, element_data::pf_el, element_data::str_e, element_data::strain, element_data::strainp, and element_data::stress.
Referenced by main_3d().
subroutine force_balance (integer n)
Definition at line 100 of file flac.f90.
References node_data::balance, node_data::cord, node_data::force, element_data::nop, sizes::side, and element_data::stress.
Referenced by bc_stress(), drop(), and efdlm().
subroutine n_force_balance (real(kind=8) dt)
Definition at line 160 of file flac.f90.
References node_data::balance, sizes::demf, sizes::den_scale, element_data::flag, node_data::force, boundary_node_data::force_code, sizes::g, node_data::mass, sizes::nbp, sizes::ne, element_data::nos, sizes::np, boundary_node_data::numbn, boundary_node_data::value, node_data::vel, and boundary_node_data::vel_code.
Referenced by drop(), and efdlm().