Hydro-PED: iaja.f File Reference
iaja.f File Reference
Functions/Subroutines
program arrays
subroutine MC57AD (LCNTL, NMAX, NELT, ELTVAR, ELTPTR, AELT, N, LIRN, IRN, IP, LA, A, IW, LP, INFO)
subroutine MC57BD (N, YESA, LA, A, NZ, IRN, IP)
Function Documentation
program arrays ()
Definition at line 30 of file iaja.f.
References MC57AD().
subroutine MC57AD (LOGICAL,dimension(10) LCNTL, INTEGER NMAX, INTEGER NELT, INTEGER,dimension(*) ELTVAR, INTEGER,dimension(nelt+1) ELTPTR, DOUBLE PRECISION,dimension(*) AELT, INTEGER N, INTEGER LIRN, INTEGER,dimension(lirn) IRN, INTEGER,dimension(nmax+1) IP, INTEGER LA, DOUBLE PRECISION,dimension(la) A, INTEGER,dimension(2*nmax) IW, INTEGER LP, INTEGER,dimension(10) INFO)
Definition at line 124 of file iaja.f.
References MC57BD().
Referenced by arrays().
subroutine MC57BD (INTEGER N, LOGICAL YESA, INTEGER LA, DOUBLE PRECISION,dimension(la) A, INTEGER NZ, INTEGER,dimension(nz) IRN, INTEGER,dimension(n) IP)
Definition at line 652 of file iaja.f.
Referenced by MC57AD().