Hydro-PED: input.f90 File Reference
input.f90 File Reference
Functions/Subroutines
subroutine input
Read and generate all necessary input data and allocate arrays.
subroutine volume_correct_sign (n)
Check if element node numbers are assined in the correct order.
Function Documentation
subroutine input ()
Read and generate all necessary input data and allocate arrays.
Read coordinates, lithology, element connections, and boundary conditions. boundary conditions. Generate initial conditions. Set material properties to each element gradient and rock stress forcing. Uses implicit time step. using the lithology.
Parameters:
[in] @param[out] All initial values, boundary conditions, and material properties.
Definition at line 40 of file input.f90.
References diffusion_data::a_matrix, element_data::al_biot, element_data::alpha, node_data::balance, diffusion_data::bc_dfval, node_data::cord, element_data::coupl, diffusion_data::d, element_data::dalpha, sizes::ddm, element_data::dens, node_data::disp, diffusion_data::displ, element_data::dphi, node_data::dspt, element_data::ductile, element_data::el_drop, element_data::el_vol, diffusion_data::f, diffusion_data::f1, element_data::field, element_data::flag, node_data::force, boundary_node_data::force_code, element_data::gr, element_data::i1, element_data::i2, diffusion_data::ia, diffusion_data::id, diffusion_data::idt, diffusion_data::ija, diffusion_data::ja, sizes::ke, element_data::ksi, element_data::ksi0, element_data::ksif, element_data::lambda, element_data::m_biot, node_data::mass, diffusion_data::mat_size, element_data::mu, sizes::nbp, sizes::ne, element_data::nop, element_data::nos, sizes::np, sizes::nprocs, element_data::num_drop, boundary_node_data::numbn, diffusion_data::order, diffusion_data::p, element_data::pf_el, node_data::pfluid, element_data::phi, element_data::phi_eq, sizes::power, diffusion_data::q, element_data::rate, diffusion_data::s, diffusion_data::shpp, element_data::str_e, element_data::strain, element_data::strain0, element_data::strainp, element_data::stress, element_data::stress0, diffusion_data::tl, sizes::tsc, diffusion_data::ul, boundary_node_data::value, node_data::vel, boundary_node_data::vel_code, volume_correct_sign(), sizes::vp2, diffusion_data::xl, diffusion_data::xsj, and element_data::zi_el.
Referenced by main_3d().
subroutine volume_correct_sign (integer n)
Check if element node numbers are assined in the correct order.
Describing the elements by their nodes must be in the correct order to avoid negative values. If the nodes are listed in file "elements.dat" in the wrong order, the determinant (volume) of the tetrahedron will be negative. volume_correct_sign will write check for this order and stop the simulation if the order is incorrect
Parameters:
[in] element node connectivity
[out]
Definition at line 677 of file input.f90.
References node_data::cord, and element_data::nop.
Referenced by input().