Hydro-PED: drop.f90 File Reference
drop.f90 File Reference
Functions/Subroutines
subroutine drop (time, dt)
Calculates stress drop in failed elements.
subroutine ksi_final (n)
Function Documentation
subroutine drop (real(kind=8) time, real(kind=8) dt)
Calculates stress drop in failed elements.
Uses explicit time step for iterrative solution of equations of motion. Append data to file "catalog" with information about failed elements
Parameters:
[in] time,time step
[out] None
Definition at line 39 of file drop.f90.
References sizes::adp, element_data::al_biot, element_data::alpha, node_data::balance, sizes::boff, boff_calc(), sizes::boff_max, sizes::boff_min, element_data::coupl, sizes::den_scale, element_data::el_drop, element_data::el_vol, elastic(), element_data::field, element_data::flag, node_data::force, force_balance(), element_data::gr, element_data::i1, element_data::i2, element_data::ksi, element_data::ksi0, ksi_final(), element_data::ksif, element_data::lambda, element_data::m_biot, move_grid(), element_data::mu, n_force_balance(), sizes::ne, element_data::num_drop, element_data::pf_el, element_data::phi, sizes::power, element_data::rate, element_data::str_e, element_data::strain, element_data::strain0, strain_invariants(), element_data::strainp, element_data::stress, element_data::stress0, sizes::vp2, and element_data::zi_el.
Referenced by main_3d().
subroutine ksi_final (integer n)
Definition at line 411 of file drop.f90.
References element_data::alpha, element_data::coupl, element_data::i1, element_data::i2, element_data::ksi, element_data::ksi0, element_data::ksif, element_data::num_drop, element_data::phi, sizes::power, and strain_invariants().
Referenced by drop().