Hydro-PED: elastic.f90 File Reference
elastic.f90 File Reference
Functions/Subroutines
subroutine elastic (n, event, s)
Calculates stress tensor for elastic strains.
subroutine strain_invariants (n, si2)
Function Documentation
subroutine elastic (integer n, logical event, real(kind=8),dimension(6) s)
Calculates stress tensor for elastic strains.
Test for convexity and calculates stress s=(sxx,syy,szz,sxy,sxz,syz) for stable element Define the flag value according to the rule: flg = 0 - stable flg = 1 - 1-st type of failure flg = 2 - 2-nd type of failure flg = 3 - open space
calculates second invariant i2(n) and strain invariant ratio ksi(n) event = true means failed element
Parameters:
[in] n - element number
[out] event=true/false; s - stress tensor
Definition at line 58 of file elastic.f90.
References element_data::alpha, element_data::flag, element_data::gr, element_data::i1, element_data::ksi, element_data::ksi0, element_data::lambda, element_data::mu, element_data::str_e, and strain_invariants().
Referenced by drop(), and efdlm().
subroutine strain_invariants (integer n, real(kind=8) si2)
Definition at line 118 of file elastic.f90.
References element_data::i1, element_data::i2, element_data::ksi, and element_data::str_e.
Referenced by drop(), elastic(), and ksi_final().