Hydro-PED: main_3d.f90 File Reference
main_3d.f90 File Reference
Functions/Subroutines
program main_3d
Function Documentation
program main_3d ()
Definition at line 32 of file main_3d.f90.
References sizes::adp, sizes::boff, sizes::boff_max, sizes::boff_min, element_data::dalpha, damage(), sizes::demf, sizes::den_scale, diffusion(), node_data::disp, drop(), node_data::dspt, efdlm(), sizes::g, diffusion_data::ia, input(), diffusion_data::ja, move_grid(), node_mass(), sizes::np, output(), plastic(), sizes::tsc, and sizes::vp2.