Hydro-PED: move_grid.f90 File Reference
move_grid.f90 File Reference
Functions/Subroutines
subroutine move_grid (dt)
Moves nodes and calculates strains.
Function Documentation
subroutine move_grid (real(kind=8) dt)
Moves nodes and calculates strains.
Uses explicit time step. Calculates new node coordinates, cumulative node displacements, and incremental displacements Calculates strain rate tensor and integrate it for new total strain
Parameters:
[in] time step
[out] None
Definition at line 38 of file move_grid.f90.
References node_data::cord, derivation(), node_data::disp, node_data::dspt, sizes::ne, element_data::nop, sizes::np, element_data::strain, and node_data::vel.
Referenced by drop(), and main_3d().