Hydro-PED: diffusion_data Module Reference
diffusion_data Module Reference
Variables
integer mat_size
integer, dimension(:), allocatable id
integer, dimension(:), allocatable idt
integer, dimension(:), allocatable order
integer, dimension(:), allocatable ja
integer(kind=c_size_t),
dimension(:), allocatable ia
integer, dimension(:,:),
allocatable ija
real(kind=8), dimension(:),
allocatable bc_dfval
real(kind=8), dimension(:),
allocatable bc_tval
real(kind=8), dimension(:),
allocatable f
real(kind=8), dimension(:),
allocatable f1
real(kind=8), dimension(:),
allocatable ft
real(kind=8), dimension(:),
allocatable ft1
real(kind=8), dimension(:),
allocatable xsj
real(kind=c_double), dimension(:),
allocatable a_matrix
real(kind=8), dimension(:,:),
allocatable d
real(kind=8), dimension(:,:),
allocatable q
real(kind=8), dimension(:,:),
allocatable ul
real(kind=8), dimension(:,:),
allocatable tl
real(kind=8), dimension(:,:),
allocatable p
real(kind=8), dimension(:,:,:),
allocatable xl
real(kind=8), dimension(:,:,:),
allocatable shpp
real(kind=8), dimension(:,:,:),
allocatable s
real(kind=8), dimension(:,:,:),
allocatable displ
Variable Documentation
real(kind=c_double),dimension(:),allocatable diffusion_data::a_matrix
Definition at line 77 of file modules.f90.
Referenced by diffusion(), finalize_solver_(), initialize_solver_(), input(), modify2(), and run_solver_().
real(kind=8),dimension(:),allocatable diffusion_data::bc_dfval
Definition at line 76 of file modules.f90.
Referenced by diffusion(), fluxbc(), and input().
real(kind=8),dimension(:),allocatable diffusion_data::bc_tval
Definition at line 76 of file modules.f90.
real(kind=8),dimension(:,:),allocatable diffusion_data::d
Definition at line 78 of file modules.f90.
Referenced by diffusion(), flux(), input(), and tetra4().
real(kind=8),dimension(:,:,:),allocatable diffusion_data::displ
Definition at line 79 of file modules.f90.
Referenced by diffusion(), input(), and tetra4().
real(kind=8),dimension(:),allocatable diffusion_data::f
Definition at line 76 of file modules.f90.
Referenced by diffusion(), input(), and modify2().
real(kind=8),dimension(:),allocatable diffusion_data::f1
Definition at line 76 of file modules.f90.
Referenced by diffusion(), input(), and modify2().
real(kind=8),dimension(:),allocatable diffusion_data::ft
Definition at line 76 of file modules.f90.
real(kind=8),dimension(:),allocatable diffusion_data::ft1
Definition at line 76 of file modules.f90.
integer(kind=c_size_t),dimension(:),allocatable diffusion_data::ia
Definition at line 74 of file modules.f90.
Referenced by input(), main_3d(), and modify2().
integer,dimension(:),allocatable diffusion_data::id
Definition at line 73 of file modules.f90.
Referenced by input(), and modify2().
integer,dimension(:),allocatable diffusion_data::idt
Definition at line 73 of file modules.f90.
Referenced by input().
integer,dimension(:,:),allocatable diffusion_data::ija
Definition at line 75 of file modules.f90.
Referenced by diffusion(), and input().
integer,dimension(:),allocatable diffusion_data::ja
Definition at line 73 of file modules.f90.
Referenced by input(), main_3d(), and modify2().
integer diffusion_data::mat_size
Definition at line 72 of file modules.f90.
Referenced by input().
integer,dimension(:),allocatable diffusion_data::order
Definition at line 73 of file modules.f90.
Referenced by input().
real(kind=8),dimension(:,:),allocatable diffusion_data::p
Definition at line 78 of file modules.f90.
Referenced by diffusion(), input(), and tetra4().
real(kind=8),dimension(:,:),allocatable diffusion_data::q
Definition at line 78 of file modules.f90.
Referenced by diffusion(), fluxbc(), and input().
real(kind=8),dimension(:,:,:),allocatable diffusion_data::s
Definition at line 79 of file modules.f90.
Referenced by diffusion(), flux(), input(), and tetra4().
real(kind=8),dimension(:,:,:),allocatable diffusion_data::shpp
Definition at line 79 of file modules.f90.
Referenced by diffusion(), and input().
real(kind=8),dimension(:,:),allocatable diffusion_data::tl
Definition at line 78 of file modules.f90.
Referenced by input().
real(kind=8),dimension(:,:),allocatable diffusion_data::ul
Definition at line 78 of file modules.f90.
Referenced by diffusion(), flux(), input(), and tetra4().
real(kind=8),dimension(:,:,:),allocatable diffusion_data::xl
Definition at line 79 of file modules.f90.
Referenced by diffusion(), flux(), input(), shape(), and tetra4().
real(kind=8),dimension(:),allocatable diffusion_data::xsj
Definition at line 76 of file modules.f90.
Referenced by diffusion(), and input().