Hydro-PED: sizes Module Reference
sizes Module Reference
Variables
integer ne
integer np
integer nbp
integer ke
integer noff
integer nprocs
integer, dimension(3, 4) side = reshape([2
real(kind=8), dimension(3) g
real(kind=8) adp
real(kind=8) den_scale
real(kind=8) boff
real(kind=8) vp2
real(kind=8) tsc
real(kind=8) ddm
real(kind=8) demf
real(kind=8) boff_min
real(kind=8) boff_max
real(kind=8) power
Variable Documentation
real(kind=8) sizes::adp
Definition at line 36 of file modules.f90.
Referenced by drop(), and main_3d().
real(kind=8) sizes::boff
Definition at line 36 of file modules.f90.
Referenced by boff_calc(), drop(), and main_3d().
real(kind=8) sizes::boff_max
Definition at line 36 of file modules.f90.
Referenced by drop(), and main_3d().
real(kind=8) sizes::boff_min
Definition at line 36 of file modules.f90.
Referenced by drop(), and main_3d().
real(kind=8) sizes::ddm
Definition at line 36 of file modules.f90.
Referenced by input().
real(kind=8) sizes::demf
Definition at line 36 of file modules.f90.
Referenced by main_3d(), and n_force_balance().
real(kind=8) sizes::den_scale
Definition at line 36 of file modules.f90.
Referenced by drop(), main_3d(), and n_force_balance().
real(kind=8),dimension(3) sizes::g
Definition at line 36 of file modules.f90.
Referenced by bc_stress(), main_3d(), and n_force_balance().
integer sizes::ke
Definition at line 34 of file modules.f90.
Referenced by input().
integer sizes::nbp
Definition at line 34 of file modules.f90.
Referenced by bc_stress(), input(), and n_force_balance().
integer sizes::ne
Definition at line 34 of file modules.f90.
Referenced by bc_stress(), damage(), diffusion(), drop(), efdlm(), input(), move_grid(), n_force_balance(), node_mass(), output(), and plastic().
integer sizes::noff
Definition at line 34 of file modules.f90.
Referenced by boff_calc().
integer sizes::np
Definition at line 34 of file modules.f90.
Referenced by boff_calc(), input(), main_3d(), modify2(), move_grid(), n_force_balance(), and output().
integer sizes::nprocs
Definition at line 34 of file modules.f90.
Referenced by input().
real(kind=8) sizes::power
Definition at line 36 of file modules.f90.
Referenced by damage(), drop(), input(), and ksi_final().
integer,dimension(3,4) sizes::side = reshape([2
Definition at line 35 of file modules.f90.
Referenced by force_balance().
real(kind=8) sizes::tsc
Definition at line 36 of file modules.f90.
Referenced by input(), and main_3d().
real(kind=8) sizes::vp2
Definition at line 36 of file modules.f90.
Referenced by drop(), input(), and main_3d().