Hydro-PED: element_data Module Reference
element_data Module Reference
Variables
integer, dimension(:), allocatable flag
integer, dimension(:), allocatable el_drop
integer, dimension(:), allocatable num_drop
integer, dimension(:,:),
allocatable nop
integer, dimension(:,:),
allocatable nos
real(kind=8), dimension(:),
allocatable lambda
real(kind=8), dimension(:),
allocatable mu
real(kind=8), dimension(:),
allocatable gr
real(kind=8), dimension(:),
allocatable dens
real(kind=8), dimension(:),
allocatable el_vol
real(kind=8), dimension(:),
allocatable al_biot
real(kind=8), dimension(:),
allocatable m_biot
real(kind=8), dimension(:),
allocatable phi
real(kind=8), dimension(:),
allocatable dphi
real(kind=8), dimension(:),
allocatable zi_el
real(kind=8), dimension(:),
allocatable alpha
real(kind=8), dimension(:),
allocatable dalpha
real(kind=8), dimension(:),
allocatable i1
real(kind=8), dimension(:),
allocatable i2
real(kind=8), dimension(:),
allocatable ksi
real(kind=8), dimension(:),
allocatable ksi0
real(kind=8), dimension(:),
allocatable ksif
real(kind=8), dimension(:),
allocatable pf_el
real(kind=8), dimension(:,:),
allocatable rate
real(kind=8), dimension(:,:),
allocatable phi_eq
real(kind=8), dimension(:,:),
allocatable ductile
real(kind=8), dimension(:,:),
allocatable coupl
real(kind=8), dimension(:,:),
allocatable stress
real(kind=8), dimension(:,:),
allocatable strain
real(kind=8), dimension(:,:),
allocatable strainp
real(kind=8), dimension(:,:),
allocatable str_e
real(kind=8), dimension(:,:),
allocatable stress0
real(kind=8), dimension(:,:),
allocatable strain0
real(kind=8), dimension(:,:),
allocatable field
Variable Documentation
real(kind=8),dimension(:),allocatable element_data::al_biot
Definition at line 46 of file modules.f90.
Referenced by drop(), efdlm(), and input().
real(kind=8),dimension(:),allocatable element_data::alpha
Definition at line 47 of file modules.f90.
Referenced by damage(), diffusion(), drop(), efdlm(), elastic(), input(), ksi_final(), and output().
real(kind=8),dimension(:,:),allocatable element_data::coupl
Definition at line 48 of file modules.f90.
Referenced by damage(), drop(), input(), and ksi_final().
real(kind=8),dimension(:),allocatable element_data::dalpha
Definition at line 47 of file modules.f90.
Referenced by damage(), input(), main_3d(), and plastic().
real(kind=8),dimension(:),allocatable element_data::dens
Definition at line 45 of file modules.f90.
Referenced by input(), and node_mass().
real(kind=8),dimension(:),allocatable element_data::dphi
Definition at line 46 of file modules.f90.
Referenced by damage(), and input().
real(kind=8),dimension(:,:),allocatable element_data::ductile
Definition at line 48 of file modules.f90.
Referenced by input(), and plastic().
integer,dimension(:),allocatable element_data::el_drop
Definition at line 43 of file modules.f90.
Referenced by drop(), and input().
real(kind=8),dimension(:),allocatable element_data::el_vol
Definition at line 46 of file modules.f90.
Referenced by drop(), input(), and node_mass().
real(kind=8),dimension(:,:),allocatable element_data::field
Definition at line 50 of file modules.f90.
Referenced by drop(), and input().
integer,dimension(:),allocatable element_data::flag
Definition at line 43 of file modules.f90.
Referenced by damage(), derivation(), drop(), efdlm(), elastic(), input(), n_force_balance(), and plastic().
real(kind=8),dimension(:),allocatable element_data::gr
Definition at line 45 of file modules.f90.
Referenced by damage(), drop(), elastic(), and input().
real(kind=8),dimension(:),allocatable element_data::i1
Definition at line 47 of file modules.f90.
Referenced by damage(), drop(), elastic(), input(), ksi_final(), and strain_invariants().
real(kind=8),dimension(:),allocatable element_data::i2
Definition at line 47 of file modules.f90.
Referenced by damage(), drop(), input(), ksi_final(), and strain_invariants().
real(kind=8),dimension(:),allocatable element_data::ksi
Definition at line 47 of file modules.f90.
Referenced by damage(), drop(), elastic(), input(), ksi_final(), and strain_invariants().
real(kind=8),dimension(:),allocatable element_data::ksi0
Definition at line 47 of file modules.f90.
Referenced by damage(), drop(), elastic(), input(), and ksi_final().
real(kind=8),dimension(:),allocatable element_data::ksif
Definition at line 47 of file modules.f90.
Referenced by drop(), input(), and ksi_final().
real(kind=8),dimension(:),allocatable element_data::lambda
Definition at line 45 of file modules.f90.
Referenced by damage(), drop(), elastic(), and input().
real(kind=8),dimension(:),allocatable element_data::m_biot
Definition at line 46 of file modules.f90.
Referenced by drop(), and input().
real(kind=8),dimension(:),allocatable element_data::mu
Definition at line 45 of file modules.f90.
Referenced by damage(), drop(), elastic(), and input().
integer,dimension(:,:),allocatable element_data::nop
Definition at line 44 of file modules.f90.
Referenced by derivation(), diffusion(), force_balance(), input(), move_grid(), node_mass(), and volume_correct_sign().
integer,dimension(:,:),allocatable element_data::nos
Definition at line 44 of file modules.f90.
Referenced by input(), and n_force_balance().
integer,dimension(:),allocatable element_data::num_drop
Definition at line 43 of file modules.f90.
Referenced by damage(), drop(), input(), and ksi_final().
real(kind=8),dimension(:),allocatable element_data::pf_el
Definition at line 47 of file modules.f90.
Referenced by diffusion(), drop(), efdlm(), and input().
real(kind=8),dimension(:),allocatable element_data::phi
Definition at line 46 of file modules.f90.
Referenced by damage(), drop(), input(), ksi_final(), and output().
real(kind=8),dimension(:,:),allocatable element_data::phi_eq
Definition at line 48 of file modules.f90.
Referenced by damage(), and input().
real(kind=8),dimension(:,:),allocatable element_data::rate
Definition at line 48 of file modules.f90.
Referenced by damage(), drop(), and input().
real(kind=8),dimension(:,:),allocatable element_data::str_e
Definition at line 49 of file modules.f90.
Referenced by drop(), efdlm(), elastic(), input(), output(), and strain_invariants().
real(kind=8),dimension(:,:),allocatable element_data::strain
Definition at line 49 of file modules.f90.
Referenced by damage(), drop(), efdlm(), input(), and move_grid().
real(kind=8),dimension(:,:),allocatable element_data::strain0
Definition at line 50 of file modules.f90.
Referenced by drop(), and input().
real(kind=8),dimension(:,:),allocatable element_data::strainp
Definition at line 49 of file modules.f90.
Referenced by damage(), drop(), efdlm(), input(), and plastic().
real(kind=8),dimension(:,:),allocatable element_data::stress
Definition at line 49 of file modules.f90.
Referenced by damage(), drop(), efdlm(), force_balance(), input(), output(), and plastic().
real(kind=8),dimension(:,:),allocatable element_data::stress0
Definition at line 50 of file modules.f90.
Referenced by drop(), and input().
real(kind=8),dimension(:),allocatable element_data::zi_el
Definition at line 46 of file modules.f90.
Referenced by drop(), input(), and output().