Hydro-PED: node_data Module Reference
node_data Module Reference
Variables
real(kind=8), dimension(:),
allocatable mass
real(kind=8), dimension(:),
allocatable pfluid
real(kind=8), dimension(:,:),
allocatable balance
real(kind=8), dimension(:,:),
allocatable cord
real(kind=8), dimension(:,:),
allocatable disp
real(kind=8), dimension(:,:),
allocatable vel
real(kind=8), dimension(:,:),
allocatable dspt
real(kind=8), dimension(:,:),
allocatable force
Variable Documentation
real(kind=8),dimension(:,:),allocatable node_data::balance
Definition at line 58 of file modules.f90.
Referenced by boff_calc(), drop(), efdlm(), force_balance(), input(), and n_force_balance().
real(kind=8),dimension(:,:),allocatable node_data::cord
Definition at line 58 of file modules.f90.
Referenced by derivation(), diffusion(), fluxbc(), force_balance(), input(), move_grid(), node_mass(), output(), and volume_correct_sign().
real(kind=8),dimension(:,:),allocatable node_data::disp
Definition at line 58 of file modules.f90.
Referenced by diffusion(), input(), main_3d(), and move_grid().
real(kind=8),dimension(:,:),allocatable node_data::dspt
Definition at line 58 of file modules.f90.
Referenced by input(), main_3d(), move_grid(), and output().
real(kind=8),dimension(:,:),allocatable node_data::force
Definition at line 59 of file modules.f90.
Referenced by bc_stress(), boff_calc(), drop(), efdlm(), force_balance(), input(), and n_force_balance().
real(kind=8),dimension(:),allocatable node_data::mass
Definition at line 57 of file modules.f90.
Referenced by bc_stress(), input(), n_force_balance(), and node_mass().
real(kind=8),dimension(:),allocatable node_data::pfluid
Definition at line 57 of file modules.f90.
Referenced by diffusion(), input(), and output().
real(kind=8),dimension(:,:),allocatable node_data::vel
Definition at line 58 of file modules.f90.
Referenced by boff_calc(), input(), move_grid(), and n_force_balance().