Hydro-PED: boundary_node_data Module Reference
boundary_node_data Module Reference
Variables
logical, dimension(:,:),
allocatable vel_code
logical, dimension(:,:),
allocatable force_code
integer, dimension(:), allocatable numbn
real(kind=8), dimension(:,:),
allocatable value
Variable Documentation
logical,dimension(:,:),allocatable boundary_node_data::force_code
Definition at line 64 of file modules.f90.
Referenced by bc_stress(), input(), and n_force_balance().
integer,dimension(:),allocatable boundary_node_data::numbn
Definition at line 65 of file modules.f90.
Referenced by bc_stress(), input(), and n_force_balance().
real(kind=8),dimension(:,:),allocatable boundary_node_data::value
Definition at line 66 of file modules.f90.
Referenced by bc_stress(), input(), and n_force_balance().
logical,dimension(:,:),allocatable boundary_node_data::vel_code
Definition at line 64 of file modules.f90.
Referenced by input(), and n_force_balance().