Hydro-PED: solver_t.cpp File Reference
solver_t.cpp File Reference
#include <Tpetra_Core.hpp>
#include <Tpetra_Vector.hpp>
#include <Tpetra_CrsMatrix.hpp>
#include <Tpetra_CrsMatrixMultiplyOp.hpp>
#include <Tpetra_Version.hpp>
#include <Teuchos_DefaultSerialComm.hpp>
#include <Teuchos_oblackholestream.hpp>
#include <BelosTpetraAdapter.hpp>
#include <BelosSolverFactory.hpp>
Typedefs
typedef Tpetra::Map map_type
typedef Tpetra::Vector::scalar_type scalar_type
typedef
Tpetra::Vector::local_ordinal_type local_ordinal_type
typedef
Tpetra::Vector::global_ordinal_type global_ordinal_type
typedef Tpetra::CrsMatrix crs_matrix_type
typedef Tpetra::CrsGraph crs_graph_type
typedef Tpetra::Vector vector_type
typedef Tpetra::MultiVector multivector_type
typedef Tpetra::Operator operator_type
Functions/Subroutines
void initialize_solver_ (int *a_n, int *a_nnz, size_t *a_rowptr, int *a_colind)
void run_solver_gmres_ (double *a_values, double *b_values, int *info)
void run_solver_cg_ (double *a_values, double *b_values, int *info)
void run_solver_ (std::string solverType, double *a_values, double *b_values, int *info)
void finalize_solver_ ()
Variables
RCP< const Comm< int > > comm
RCP< crs_matrix_type > a_matrix
ArrayRCP< size_t > rowPtr
ArrayRCP< global_ordinal_type > colInd
Tpetra::global_size_t numGlobalEntries
Tpetra::global_size_t numOfNnz
Typedef Documentation
typedef Tpetra::CrsGraph crs_graph_type
Definition at line 58 of file solver_t.cpp.
typedef Tpetra::CrsMatrix crs_matrix_type
Definition at line 57 of file solver_t.cpp.
typedef Tpetra::Vector ::global_ordinal_type global_ordinal_type
Definition at line 56 of file solver_t.cpp.
typedef Tpetra::Vector ::local_ordinal_type local_ordinal_type
Definition at line 55 of file solver_t.cpp.
typedef Tpetra::Map map_type
Definition at line 53 of file solver_t.cpp.
typedef Tpetra::MultiVector multivector_type
Definition at line 60 of file solver_t.cpp.
typedef Tpetra::Operator operator_type
Definition at line 61 of file solver_t.cpp.
typedef Tpetra::Vector ::scalar_type scalar_type
Definition at line 54 of file solver_t.cpp.
typedef Tpetra::Vector vector_type
Definition at line 59 of file solver_t.cpp.
Function Documentation
void finalize_solver_ ()
Definition at line 202 of file solver_t.cpp.
References diffusion_data::a_matrix.
{
    a_matrix.release();
//    a_matrix=RCP<crs_matrix_type>(new crs_matrix_type(Teuchos::null));
}
void initialize_solver_ (int * a_n, int * a_nnz, size_t * a_rowptr, int * a_colind)
Definition at line 80 of file solver_t.cpp.
References diffusion_data::a_matrix, colInd, comm, numGlobalEntries, numOfNnz, and rowPtr.
{
  comm  = RCP<const Comm<int> >(new SerialComm<int> ());
  const global_ordinal_type indexBase = 0;
  numGlobalEntries = *a_n;
  numOfNnz = *a_nnz;
  const RCP<const map_type> rowMap =
    rcp (new map_type (numGlobalEntries, indexBase, comm));
  const RCP<const map_type> colMap =
    rcp (new map_type (numGlobalEntries, indexBase, comm));
  rowPtr = ArrayRCP<size_t>(numGlobalEntries+1);
  rowPtr.deepCopy(Teuchos::ArrayView<size_t>(a_rowptr, numGlobalEntries+1));
  colInd =  ArrayRCP<global_ordinal_type>(numOfNnz);
  colInd.deepCopy(Teuchos::ArrayView<global_ordinal_type>(a_colind, numOfNnz));
  //Change Fortran indexing to CPP
  #pragma omp parallel
  {
    int i;
    #pragma omp for simd
    for (i=0;i<numGlobalEntries;++i)
    {
      rowPtr[i]--;
    }
    #pragma omp for simd
    for (i=0;i<numOfNnz;++i)
    {
      colInd[i]--;
    }
  }
  RCP<crs_graph_type> crsGraph =
    rcp (new crs_graph_type (rowMap, colMap, rowPtr, colInd));
  const RCP<ParameterList> crsGraphParameters =
    rcp (new ParameterList("CRSGraphParams"));
  crsGraph->fillComplete();
  a_matrix=RCP<crs_matrix_type>(new crs_matrix_type(crsGraph));
}
void run_solver_ (std::string solverType, double * a_values, double * b_values, int * info)
Definition at line 135 of file solver_t.cpp.
References diffusion_data::a_matrix, colInd, comm, numGlobalEntries, numOfNnz, and rowPtr.
Referenced by run_solver_cg_(), and run_solver_gmres_().
{
    const global_ordinal_type indexBase = 0;
    RCP<const map_type> rowMap =
      rcp (new map_type (numGlobalEntries, indexBase, comm));
    RCP<const map_type> colMap =
      rcp (new map_type (numGlobalEntries, indexBase, comm));
    ArrayRCP<scalar_type> values (a_values, 0, numOfNnz, false);
    a_matrix->resumeFill();
    for(size_t i=indexBase;i<indexBase+numGlobalEntries;i++)
    {
      a_matrix->replaceGlobalValues(i, rowPtr[i - indexBase +1]-rowPtr[i - indexBase],a_values+rowPtr[i - indexBase],colInd.getRawPtr()+rowPtr[i - indexBase]);
    }
    a_matrix->fillComplete();
    a_matrix->print(std::cout);
    RCP<multivector_type> x_multivector =
        rcp (new multivector_type(a_matrix->getDomainMap(), 1));
    x_multivector->print(std::cout);
    Teuchos::ArrayView<const scalar_type> b_vector(b_values, numGlobalEntries);
    Teuchos::ArrayView<const Teuchos::ArrayView<const scalar_type>> b_arrayview(&b_vector, 1);
    RCP<multivector_type> b_multivector =
        rcp (new multivector_type(a_matrix->getRangeMap(), b_arrayview, 1));
    b_multivector->print(std::cout);
    deep_copy(*x_multivector, *b_multivector);
    RCP<ParameterList> solverParams = parameterList();
    solverParams->set ("Num Blocks", 40);
    //solverParams->set ("Recycled Blocks", 20);
    solverParams->set ("Maximum Iterations", 1000);
    solverParams->set ("Convergence Tolerance", 1.0e-5);
    Belos::SolverFactory<scalar_type, multivector_type, operator_type> factory;
    RCP<Belos::SolverManager<scalar_type, multivector_type, operator_type>> solver =
        factory.create(solverType, solverParams);
    typedef Belos::LinearProblem<scalar_type, multivector_type, operator_type> problem_type;
    RCP<problem_type> problem = rcp (new problem_type(a_matrix, x_multivector, b_multivector));
    problem->setProblem();
    solver->setProblem(problem);
    Belos::ReturnType result = solver->solve();
    #pragma omp barrier
    const int numIters = solver->getNumIters();
    if(result == Belos::Converged)
    {
        std::cout << "CONVERGED! :) in " << numIters << " iterations.\n";
    }
    else
    {
        std::cout << "DIDN'T CONVERGED :(\n";
    }
    ArrayRCP<const scalar_type> new_b = x_multivector->get1dView();
    #pragma omp parallel for simd
    for (int i=0; i < numGlobalEntries; ++i)
    {
        b_values[i] = new_b[i];
    }
}
void run_solver_cg_ (double * a_values, double * b_values, int * info)
Definition at line 130 of file solver_t.cpp.
References run_solver_().
{
    run_solver_("CG", a_values, b_values, info);
}
void run_solver_gmres_ (double * a_values, double * b_values, int * info)
Definition at line 125 of file solver_t.cpp.
References run_solver_().
{
    run_solver_("GMRES", a_values, b_values, info);
}
Variable Documentation
RCP<crs_matrix_type> a_matrix
Definition at line 64 of file solver_t.cpp.
ArrayRCP<global_ordinal_type> colInd
Definition at line 66 of file solver_t.cpp.
RCP<const Comm<int> > comm
Definition at line 63 of file solver_t.cpp.
Tpetra::global_size_t numGlobalEntries
Definition at line 67 of file solver_t.cpp.
Tpetra::global_size_t numOfNnz
Definition at line 68 of file solver_t.cpp.
ArrayRCP<size_t> rowPtr
Definition at line 65 of file solver_t.cpp.